version: '3'

tasks:
  all:
    cmds:
      - task: build
      - task: extract
      - task: package-next
      - task: package-muos
    silent: true

  build:
    cmds:
      - rm -rf build
      - docker buildx build --platform=linux/arm64 -t retro-console-arm64 -f Dockerfile .
    silent: true

  extract:
    cmds:
      - mkdir -p build
      - mkdir -p build/lib
      - docker rm extract || true
      - docker create --name extract retro-console-arm64
      - docker cp extract:/build/mortar build/mortar
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
    silent: true

  package-next:
    cmds:
      - rm -rf build/Mortar.pak || true
      - mkdir -p build/Mortar.pak
      - mkdir -p build/Mortar.pak/resources/lib
      - cp build/mortar scripts/NextUI/launch.sh README.md LICENSE pak.json build/Mortar.pak
      - cp -R build/lib build/Mortar.pak/resources
      - cp -R resources build/Mortar.pak/
    silent: true

  package-muos:
    cmds:
      - rm -rf build/muOS || true
      - mkdir -p build/muOS/Mortar
      - mkdir -p build/muOS/Mortar/resources/lib
      - cp build/mortar scripts/muOS/mux_launch.sh README.md LICENSE build/muOS/Mortar
      - cp -R build/lib build/muOS/Mortar/resources
      - cp -R resources build/muOS/Mortar/
      - cp -R fonts build/muOS/Mortar/resources
      - cp .github/resources/input_mappings/rg35xxsp_mapping.json build/muOS/Mortar/input_mapping.json
    silent: true

  adb:
    cmds:
      - adb shell rm -rf /mnt/SDCARD/Tools/tg5040/Mortar.pak || true
      - adb push build/Mortar.pak /mnt/SDCARD/Tools/tg5040
      - adb push config.yml /mnt/SDCARD/Tools/tg5040/Mortar.pak
      - say Finished deploying Mortar!
    silent: true

  kill:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof dlv)" > /dev/null 2>&1 || true
      - sshpass -p 'tina' ssh root@192.168.1.210 "kill  \$(pidof mortar)" > /dev/null 2>&1 || true
    silent: true

  debug:
    cmds:
      - sshpass -p 'tina' ssh root@192.168.1.210 "sh -c '/mnt/SDCARD/Developer/bin/dlv attach --headless --listen=:2345 --api-version=2 --accept-multiclient \$(pidof mortar)'" > /dev/null &
      - printf "Press any key to quit debugging...\n"
      - read
      - task: kill
    silent: true
