hosts:
  - display_name: "Megathread"
    host_type: MEGATHREAD
    root_uri: "https://myrient.erista.me"

    platforms:
      - platform_name: "Game Boy"
        system_tag: "GB"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy/"
      - platform_name: "Game Boy Color"
        system_tag: "GBC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/"
      - platform_name: "Game Boy Advance"
        system_tag: "GBA"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
      - platform_name: "Nintendo Entertainment System"
        system_tag: "FC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/"
      - platform_name: "Super Nintendo Entertainment System"
        system_tag: "SFC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/"
      - platform_name: "PlayStation"
        system_tag: "PS"
        host_subdirectory: "/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/"

    filters:
      exclusive_filters:
        - "(Proto"
        - "(Demo)"
        - "(Beta)"
        - "(Aftermarket"
        - "4-in-1"
        - "4 in 1"
        - "(Europe)"
        - "(Japan)"
      inclusive_filters:
        - "USA"
        - "En,"

download_art: true
log_level: "ERROR"
